name: Pilacca
favicon: null
layout_spectrum: 0.08214
typography_spectrum: 0.0673
title: Pilacca - Fried Chili Pepper Sauce
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77742344-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#201e1f'
    - '#981701'
    - '#bbb4a1'
    - '#b95544'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
