name: Pilacca
favicon: null
layout_spectrum: 0.34696725313551724
typography_spectrum: 0.047449270030483603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9601002128329128
  lightness: 0.8888502269983292
  saturation: 0.0359247128944844
  rhythmicContrast: 0.5991910432931036
purpose: []
